<?php


function wunderkind_cms_install() {
  variable_set('site_frontpage', 'home');
  $value = file_get_contents(drupal_get_path('module', 'wunderkind_cms') . '/wunderkind_layoutbuilder_import/wunderkind_cms_layout_builder_settings.php');
  db_update('variable')->fields(array('value' => $value))->condition('name', 'nikadevs_cms_layout_wunderkind_sub')->execute();
  db_update('variable')->fields(array('value' => $value))->condition('name', 'nikadevs_cms_layout_wunderkind')->execute();
}
